print('#'*4)
print('#')
print('#')
print('#'*4)
print('#')
print('#')
print('#'*4)

print()

print('#', ' '*5, '#', sep = '')
print('#', ' '*5, '#', sep = '')
print('#', ' '*5, '#', sep = '')
print('#'*7)
print('#', ' '*5, '#', sep = '')
print('#', ' '*5, '#', sep = '')
print('#', ' '*5, '#', sep = '')
